### ISSUE TITLE
tzlocal version conflict error

### ISSUE THREAD

**Issue by alistardust** [robinhood/airflow-prometheus-exporter#16]
Hi,

We just tried installing your plugin on our docker image, which is based on the nearly ubiquitous puckel docker image for airflow, and we're now getting the error following this description about a tzlocal version conflict. It's odd because I don't see where there's a requirement for tzlocal<2.0.0,>=1.4
anywhere in your code. Our application has a requirement of >= 2.0.0. So I'm a bit confused as to why we're seeing that when installing your plugin.

Airflow version:  1.10.6
base container: python:3.7.5-slim-buster
using the KubernetesExecutor with PythonOperator
airflow installed with these options/plugins: `apache-airflow[crypto,postgres,hive,jdbc,kubernetes,statsd,ssh]`
```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 95, in <module>
    operators._integrate_plugins()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/__init__.py", line 104, in _integrate_plugins
    from airflow.plugins_manager import operators_modules
  File "/usr/local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 167, in <module>
    plugins
  File "/usr/local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 104, in load_entrypoint_plugins
    plugin_obj = entry_point.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tzlocal 2.0.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('tzlocal<2.0.0,>=1.4'), {'apache-airflow'})
```

**Comment by abhishekray07** [comment]
I am not entirely sure why you have a tzlocal conflict. I don't think it is due to the airflow exporter. Maybe try to get into the docker container and do `pip show tzlocal` to see why this particular version is being installed?
