### ISSUE TITLE
Airflow 2.3.2 error

### ISSUE THREAD

**Issue by llamageddon83** [robinhood/airflow-prometheus-exporter#57]
Added  `airflow-prometheus-exporter==1.0.8` to the requirements.txt and getting the following error:

```
airflow-scheduler_1  | [2022-07-05 23:10:02,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/***/dags/amadeus/anypoint_mq_subscriber.py
airflow-scheduler_1  | [2022-07-05 23:10:02,385] {plugins_manager.py:235} ERROR - Failed to import plugin AirflowPrometheus
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 227, in load_entrypoint_plugins
airflow-scheduler_1  |     plugin_class = entry_point.load()
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
airflow-scheduler_1  |     module = import_module(match.group('module'))
airflow-scheduler_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
airflow-scheduler_1  |     return _bootstrap._gcd_import(name[level:], package, level)
airflow-scheduler_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
airflow-scheduler_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
airflow-scheduler_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
airflow-scheduler_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
airflow-scheduler_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
airflow-scheduler_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow_prometheus_exporter/prometheus_exporter.py", line 9, in <module>
airflow-scheduler_1  |     from airflow.settings import RBAC, Session
airflow-scheduler_1  | ImportError: cannot import name 'RBAC' from 'airflow.settings' (/home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py)
```

localhost:8080/admin/metrics returns a 404

**Comment by llamageddon83** [comment]
@danh32 @jinatonic @edmondwong @JamshedVesuna has this repository no longer been maintained? There are two open PRs to fix this issue 🤦‍♂️

**Comment by jinatonic** [comment]
hello, I am checking internally to see who's the owner for this repo. I'm pretty sure that the original owner left the company, and I have no context here unfortunately.

**Comment by llamageddon83** [comment]
@jinatonic thank you for following up on this. Would it be possible for you to divulge if you guys are using this internally? Don't want to add this dependency if it isn't being actively maintained. And at the same time too lazy to write it myself.
